# Generated by Django 4.2.19 on 2025-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog_travel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "image",
                    models.ImageField(
                        default="author_default/author_info.jpeg",
                        upload_to="author_image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ManyToManyField(to="app_blog_travel.author"),
        ),
    ]
