# Generated by Django 4.2.19 on 2025-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog_travel", "0004_remove_post_author_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(
                default="author_default/author_info.jpeg", upload_to="author_default"
            ),
        ),
    ]
