# Generated by Django 4.2.19 on 2025-04-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog_travel", "0005_alter_author_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(
                default="first_img_author/author_info.jpeg", upload_to="author_default"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="first_img_post/my_default.jpeg", upload_to="Post_default"
            ),
        ),
    ]
