# Generated by Django 4.2.19 on 2025-04-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_travel', '0007_rename_tag_category_rename_tags_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='Categories',
        ),
    ]
