# Generated by Django 4.2.19 on 2025-03-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["published_date"]},
        ),
    ]
