# Generated by Django 4.2.19 on 2025-03-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0002_alter_post_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
    ]
