# Generated by Django 4.2.19 on 2025-04-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0002_alter_post_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
