# Generated by Django 4.2.19 on 2025-03-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0003_remove_post_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="Tags",
            field=models.ManyToManyField(to="app_travel.tag"),
        ),
    ]
