# Generated by Django 4.2.19 on 2025-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
