# Generated by Django 4.2.19 on 2025-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0004_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
