# Generated by Django 4.2.19 on 2025-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0005_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
