# Generated by Django 4.2.19 on 2025-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0006_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
